server:
  port: 8083

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://3.38.95.110:5433/${POSTGRES_SCHED_DB_NAME}
    username: ${POSTGRES_SCHED_USER}
    password: ${POSTGRES_SCHED_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.backend: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"