version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - gateway
    restart: always

  gateway:
    build: ./back/gateway
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  spring-auth:
    build: ./back/auth
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  spring-scheduler:
    build: ./back/scheduler
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  fastapi:
    build: ./back/rag
    ports:
      - "8090:8090"
    environment:
      - ENV=local

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRES_DB: ${POSTGRE_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
