version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: ["80:80", "443:443"]
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on: [gateway]
    restart: always

  gateway:
    container_name: gateway-service
    build: ./back/gateway
    command: ["java","-jar","/app/app.jar","--spring.profiles.active=prod"]
    env_file: .env.prod
    restart: always

  auth:
    container_name: auth-service
    build: ./back/auth
    command: ["java","-jar","/app/app.jar","--spring.profiles.active=prod"]
    env_file: .env.prod
    depends_on: [postgres_auth]
    restart: always

  scheduler:
    container_name: backend-service
    build: ./back/scheduler
    command: ["java","-jar","/app/app.jar","--spring.profiles.active=prod"]
    env_file: .env.prod
    depends_on: [postgres_sched]
    restart: always

  rag:
    container_name: rag-service
    build: ./back/rag
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8090"]
    env_file: .env.prod
    restart: always

  postgres_auth:
    container_name: postgres-auth
    image: postgres:15
    env_file: .env.prod
    environment:
      POSTGRES_USER:     ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_AUTH_DB_NAME}
    ports: ["5432:5432"]
    restart: always
    volumes: [pg_auth:/var/lib/postgresql/data]

  postgres_sched:
    container_name: postgres-sched
    image: postgres:15
    env_file: .env.prod
    environment:
      POSTGRES_USER:     ${POSTGRES_SCHED_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SCHED_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_SCHED_DB_NAME}
    ports: ["5433:5432"]
    restart: always
    volumes: [pg_sched:/var/lib/postgresql/data]

volumes:
  pg_auth:
  pg_sched:
