server:
  port: 8090  # Gateway Server 포트

spring:
  profiles:
    active: local # 기본은 local로 설정

  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://auth-service:8091  # auth 서비스의 컨테이너 이름과 포트
          predicates:
            - Path=/auth/**

        - id: llm-route
          uri: http://llm-service:8092  # llm 서비스의 컨테이너 이름과 포트
          predicates:
            - Path=/llm/**

        - id: logging-route
          uri: http://logging-service:8093  # logging 서비스의 컨테이너 이름과 포트
          predicates:
            - Path=/logging/**

        - id: test-route
          uri: https://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1