openai:
  model: 'gpt-4o-mini'
mcp:
  # In-process generic MCP 서버에 포함할 툴들
  tools:
    - filesystem
    - shell
    - docker
    - http
    - git
    - database
    - memory
    - github
    - slack
    - pinecone
    - redis
    - quickchart
    - playwright
    - postman
    - replicate
    - tmdb
    - telegram
